### ISSUE TITLE
it is unable to find images from certain albums

### ISSUE THREAD

**Issue by davidmason181017** [Lucas8x/luscious-downloader#1]
heya i have been using this striper for a few days and ran into a problem with it so i figured that i should bring it to your attention

**Comment by Lucas8x** [comment]
> heya i have been using this striper for a few days and ran into a problem with it so i figured that i should bring it to your attention

Which albums?

**Comment by davidmason181017** [comment]
https://members.luscious.net/albums/lolis-are-not-just-for-patting_319884/
this is the first one i found the issue with but there were a couple of other ones
