### ISSUE TITLE
problem with the version of python which my computer says isnt compatable with it

### ISSUE THREAD

**Issue by davidmason181017** [Lucas8x/luscious-downloader#10]
i have used this programs for a bit and had to reinstall windows and i now get this error when i try to use it
![Annotation 2020-05-17 002643](https://user-images.githubusercontent.com/58480808/82122157-374f6600-97d5-11ea-90cc-5138987c90b9.png)

**Comment by Lucas8x** [comment]
What's your version of windows?
do you have [Visual C ++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-US/download/details.aspx?id=48145) installed?

**Comment by davidmason181017** [comment]
just installed it it's working fine sorry for the trouble
