### ISSUE TITLE
list.txt, list_completed.txt, and logs.log files not updating

### ISSUE THREAD

**Issue by PiPerson7472** [Lucas8x/luscious-downloader#12]
I have downloaded the newest version (4.3.0), filled my list.txt files with links to the albums I wish to download and replaced the empty list_completed.txt file with my already full list_completed.txt file as well as the logs.log file. 

The download itself so far has been fine but previously I could check to see how many albums are left by going into the list.txt and seeing how many lines (links) are left. However this time all of the original lines (links) are still present. So I checked the list_completed.txt and logs.log files and noticed the same. The files are not being updated with what has been done with the albums, whether that be an error, completed, or in the queue.

**Comment by Lucas8x** [comment]
Sorry about that, now the list and logs should work.
