### ISSUE TITLE
'lsd' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by starcestus** [Lucas8x/luscious-downloader#13]
I know I am doing something wrong here but I installed the tool but when I try to run it I get this error

'lsd' is not recognized as an internal or external command,
operable program or batch file.

and i get syntax errors when running from pything.exe in CMD

I also created a .py file  with this text but nothing happens

import lsd

lsd -u https://members.luscious.net/users/668124/

**Comment by Lucas8x** [comment]
Your python is probably not in the windows path.
Select add python to PATH in the installer: [Photo](https://docs.python.org/3/_images/win_installer.png)
Or look this: [How to add Python to Windows PATH](https://datatofish.com/add-python-to-windows-path/)

**Comment by starcestus** [comment]
I just reinstalled python and made sure that with was added to PATH im using 3.8.6 idk if  that matters could you give me an example of the full line of code? i know im missing something super simple but nothing im trying seeems to work

**Comment by starcestus** [comment]
i figured it out thanks
