### ISSUE TITLE
window  installation version not working 

### ISSUE THREAD

**Issue by jumbonut** [Lucas8x/luscious-downloader#21]
i keep getting this message when trying to download albums 

[12:19:30] [ERROR] Failed to download picture: https://cdnio.luscious.net/Pintudo/548/lusciousnet_lusciousnet_yuri2016051010_467190755.jpg
[Errno 2] No such file or directory: 'albums\\Light Yuri\\lusciousnet_lusciousnet_yuri2016051010_467190755.jpg'
![Screenshot 2021-06-26 122743](https://user-images.githubusercontent.com/86529069/123519552-013c1100-d67a-11eb-98e1-4668aefcc8ae.jpg)

**Comment by Lucas8x** [comment]
Sorry for the delay, now it's fixed.
Please download again to get the latest update.
^^

**Comment by jumbonut** [comment]
It works know, thank you for your hard work ^^
