### ISSUE TITLE
Error when running search.

### ISSUE THREAD

**Issue by darkangelvenom** [Lucas8x/luscious-downloader#22]
When running the search function i get this error:

[20:42:33] [INFO] Total of 1439 links found.
Traceback (most recent call last):
  File "C:\Users\user\Desktop\luscious-downloader-main\luscious_dl\menu.py", line 107, in <module>
    menu()
  File "C:\Users\user\Desktop\luscious-downloader-main\luscious_dl\menu.py", line 85, in menu
    start(args)
  File "C:\Users\user\Desktop\luscious-downloader-main\luscious_dl\start.py", line 131, in start
    album_folder = Path.joinpath(args.output_dir, formmatted_foldername)
  File "pathlib.py", line 962, in joinpath
AttributeError: 'NoneType' object has no attribute '_make_child'
Press any key to continue . . .

**Comment by Lucas8x** [comment]
Maybe related to #21 
if you can download the latest update and try again.

If it still doesn't work, just to find out have you modified any of these settings:
"directory" or "foldername_format" ?

If the problem still persists please try if you can send a photo or text of the terminal, I would appreciate it ^^

**Comment by darkangelvenom** [comment]
redownloaded and ran the run.bat file and immediately tried the search function with the same error

C:\Users\****s>pip install luscious-downloader
Defaulting to user installation because normal site-packages is not writeable
Collecting luscious-downloader
  Downloading luscious_downloader-4.8.1-py3-none-any.whl (17 kB)
Collecting requests>=2.25
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting tabulate>=0.8.7
  Using cached tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting colorlog>=5
  Using cached colorlog-5.0.1-py2.py3-none-any.whl (10 kB)
Collecting colorama
  Using cached colorama-0.4.4-py2.py3-none-any.whl (16 kB)
Collecting chardet<5,>=3.0.2
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2021.5.30-py2.py3-none-any.whl (145 kB)
Collecting idna<3,>=2.5
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Collecting urllib3<1.27,>=1.21.1
  Using cached urllib3-1.26.6-py2.py3-none-any.whl (138 kB)
Installing collected packages: urllib3, idna, colorama, chardet, certifi, tabulate, requests, colorlog, luscious-downloader
  WARNING: The script chardetect.exe is installed in 'C:\Users\****s\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script tabulate.exe is installed in 'C:\Users\****s\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script lsd.exe is installed in 'C:\Users\****s\AppData\Roaming\Python\Python39\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed certifi-2021.5.30 chardet-4.0.0 colorama-0.4.4 colorlog-5.0.1 idna-2.10 luscious-downloader-4.8.1 requests-2.25.1 tabulate-0.8.9 urllib3-1.26.6


The script can be terminated at any time by pressing Ctrl-C or clicking X
-------------------------------------------------------------------------
[18:21:44] [INFO] Luscious Downloader version: 4.8.1
Options:
1 - Download albums by URL or ID.
2 - Download all user albums.
3 - Download all user favorites.
4 - Search albums by keyword.
5 - Download albums from list.txt.
6 - Settings.
0 - Exit.
> 4
Enter keyword
> yuri
Enter starting page number or leave blank
>
Enter max page or leave blank
>
Download search results? ("Y/N") y
[18:22:18] [MSG] Searching albums with keyword: yuri | Page: 1 | Max pages: 1 | Sort: date_trending
[18:22:18] [MSG] Search Result Total: 30
    ID  Title                             Pictures    Gifs  Author
------  ------------------------------  ----------  ------  ----------------
263227  Yuri                                    20       0  smartguy1234
328552  Yuri Hentai                             40       0  KrayNeko
269072  Yuri                                    64       2  ansatsuken97
 65874  Fingering Yuri                         153       0  LesbianHentai91
396727  Yuri                                   629      24  greatdayhero
101436  Yuri                                    30       0  Edwynn
 60628  Dildo Yuri                             102       0  LesbianHentai91
290119  Sweet Yuri!                            140       0  HentaiFan1701
 62839  Yuri                                   151       0  tacosanta
101115  Best of Yurizan                        217       0  Hive Mind
357217  Yuri                                    54       1  猫少女メイド
283637  Yuri                                   389       0  Ruby
 94416  Hentai Yuri                             96       0  eBonyStyle
 56372  Yuri - 5                               141       0  trippinsweet
331281  yuris                                 1606       0  lycan74
 55825  Yuri                                    67       0  trippinsweet
265823  Mira Yurizaki (Dimension W)             40       0  Maxramzz
 95004  Angel Beats Yurippe Collection          94       0  Kuroya
414627  yuri                                    98       0  Abricot sama
360607  Yuri                                   116       3  Joji_Beans
292753  Yuri                                    85       0  MaximumImpulse
406108  Yuri                                    35       0  Intact12
 82599  Yuri High Quality                      650       1  Willard30
 90403  yuri                                    95       0  sorakasuganoyuri
404332  Yuri Vault Vol 2                       747       0  Hentailuver148
350820  yuri                                   168       0  kittykatswell65
 92906  I love yuri ♥                           23       0  Lenia
270435  YurixxZobo (lesbian)                    45       6  Zoboxo
 65882  Personal Yuri Collection                76       7  TClaymore
329001  Yuri                                   313      23  Maxxy
[18:22:18] [MSG] Album information:
| ID       | 263227       |
| Title    | Yuri         |
| Author   | smartguy1234 |
| Pictures | 20           |
| Gifs     | 0            |
[18:22:18] [MSG] Fetching album pictures...
[18:22:18] [INFO] Total of 20 links found.
Traceback (most recent call last):
  File "C:\Users\****s\Desktop\luscious-downloader-main (2)\luscious-downloader-main\luscious_dl\menu.py", line 107, in <module>
    menu()
  File "C:\Users\****s\Desktop\luscious-downloader-main (2)\luscious-downloader-main\luscious_dl\menu.py", line 85, in menu
    start(args)
  File "C:\Users\****s\Desktop\luscious-downloader-main (2)\luscious-downloader-main\luscious_dl\start.py", line 131, in start
    album_folder = Path.joinpath(args.output_dir, formmatted_foldername)
  File "pathlib.py", line 962, in joinpath
AttributeError: 'NoneType' object has no attribute '_make_child'
Press any key to continue . . .

**Comment by Lucas8x** [comment]
Thanks for helping, now it's fixed.
If you can download the latest update and try again.
^^
