### ISSUE TITLE
Works fine, but keep getting a Pillow error?

### ISSUE THREAD

**Issue by DarkeReises** [Lucas8x/luscious-downloader#26]
So, the luscious downloader works wonderfully. However, for some reason I keep getting this error at the end of every album being installed.

> [ERROR] Please install Pillow package by using pip.

It doesn't seem to affect anything, as all images are being downloaded, but I have Pillow installed and it's up to date, so I'm just confused. At first I thought it was because of having Generate PDF as true, since that function wasn't working, but it didn't seem to be the case. Speaking of, I'd like help with that too, since it doesn't seem to do anything while having it on.

I'm using Windows, and I used the package with the run.bat to install it.

 I'm no coder, and I only have python and such for stuff like this, so I don't know how anything works. Would appreciate help, thanks.

**Comment by Lucas8x** [comment]
I didn't explain that part sorry .-.
As you are running by run.bat try this if you want to generate pdf:

- Go to root folder
- Hold shift + right click
- Open your terminal
- Enter: `python\python.exe -m pip install Pillow`

If not just disable pdf generation in settings
from the menu press 6 then 7

**Comment by DarkeReises** [comment]
Thanks a bunch, it's working now. Guess it's cause I installed Pillow with the python3 command rather than python\python.exe? That's the only thing that was different.

**Comment by Lucas8x** [comment]
Exactly ^^, when run by `run.bat` the packages are installed in an isolated environment apart from your system.
