### ISSUE TITLE
Possibly Niche Request

### ISSUE THREAD

**Issue by DarkeReises** [Lucas8x/luscious-downloader#28]
I was wondering if it would be possible to add an option to download albums as .cbz archives for people to enable when downloading doujins. If not that, just .zip archives work since you can just change the file extension to convert it. I'm not sure how many people utilize cbz comic readers, so I'm not expecting much, since there are probably better things to focus on lol.

**Comment by Lucas8x** [comment]
I'll check ^^

**Comment by Lucas8x** [comment]
Done, hope it's useful
