### ISSUE TITLE
Broken ?

### ISSUE THREAD

**Issue by UnknownGreen** [Lucas8x/luscious-downloader#3]
Been getting this for about 3/4 days
![image](https://user-images.githubusercontent.com/61893282/76561789-eac97080-649b-11ea-9010-3538cd9824ea.png)
no idea what it is but its happening on my computer and laptop

**Comment by Lucas8x** [comment]
Yes, they changed some things on the site

**Comment by UnknownGreen** [comment]
Will you be able to fix it so it works again ?
If yes how long will it take ?
Sorry if i sound rude

**Comment by Lucas8x** [comment]
Yes, it's possible I already fixed some things

**Comment by UnknownGreen** [comment]
Okay thank you.

**Comment by Lycantant** [comment]
thanks @Lucas8x 😁
