### ISSUE TITLE
A repeating error

### ISSUE THREAD

**Issue by PiPerson7472** [Lucas8x/luscious-downloader#7]
The downloader will loop an error without continuing on. https://members.luscious.net/albums/uncensored-hentai_272318/
https://members.luscious.net/albums/ultimate-yaoi-shotacon-album-part-3_248156/
https://members.luscious.net/albums/trisha-elricsloth_339971/
https://members.luscious.net/albums/nnum1_291994/
https://members.luscious.net/albums/my_artist_cg_collection_309064/
https://members.luscious.net/albums/my-hentai-collection-vol6_273658/
https://members.luscious.net/albums/mahou-shoujo-lyrical-nanoha_366391/
https://members.luscious.net/albums/lolicon-galore_262730/
https://members.luscious.net/albums/furry-pussies_269508/
These albums have given me this rolling error. Nothing is reported in the log and the links are still active. The downloader says it will retry picture (1) and cycle through all images in ablum without stopping.

**Comment by Lucas8x** [comment]
Infinite loop of picture (1) retries? If so, I already solved
